ALTER TABLE account_progress
  ADD COLUMN IF NOT EXISTS chapter1_revision BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chapter1_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS chapter2_revision BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chapter2_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS chapter3_revision BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chapter3_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS chapter4_revision BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chapter4_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS chapter5_revision BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chapter5_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
